### PR TITLE
Fix Empty Deck Exception not Handled

### LINKED ISSUE #128: Uncatched index error when drawing from an empty deck
- Start Game: Initiated a new game. 
- Select Deck: Chose the [4] Abandoned Deck.
- Accept Blind: Started the first round (Small Blind).
- Play Cards (Hand 1): Played cards 1,2,3,4,5. (Reduced Hands remaining to 3, removed 5 cards from deck, drew 5 new cards).
- Discard Cards (Discard 1): Discarded cards 1,2,3,4,5. (Reduced Discards remaining to 3, removed 5 cards from deck, drew 5 new cards).
- Discard Cards (Discard 2): Discarded cards 1,2,3,4,5. (Reduced Discards remaining to 2, removed 5 cards from deck, drew 5 new cards).
- Discard Cards (Discard 3): Discarded cards 1,2,3,4,5. (Reduced Discards remaining to 1, removed 5 cards from deck, drew 5 new cards).
- Discard Cards (Discard 4): Discarded cards 1,2,3,4,5. (Reduced Discards remaining to 0, removed 5 cards from deck, drew 5 new cards).
- Play Cards (Hand 2): Played cards 1,2,3,4,5. (Reduced Hands remaining to 2, removed 5 cards from deck, drew 5 new cards).
- Play Cards (Hand 3 - Error Trigger): Attempted to play cards 1,2,3,4,5.
- ERROR OCCURRED: Index 0 out of bounds for length 0

### PR DESCRIPTION
**Pull request by jwyk**
This PR fixes #128.

It was possible to run out of cards to draw from the deck, specifically for the Abandoned Deck.

This PR fixes this by reducing the `MAX_DISCARDS_PER_ROUND` to 3, matching a standard blind ruleset. An additional `JavatroException` handling this error has also been made.

Tests have also been changed to account for this change in `MAX_DISCARDS_PER_ROUND`

### CODE REVIEW

File: src/main/java/javatro/core/JavatroException.java [hunk 1]
```diff
@@ -80,6 +80,17 @@ public static JavatroException invalidDeck() {
...
+     * Creates an exception indicating the deck is empty.
+     *
+     * <p>This exception is thrown when all the cards in the deck have been drawn.
+     *
+     * @return A {@code JavatroException} indicating the deck is empty.
+     */
+    public static JavatroException noCardsRemaining() {
+        return new JavatroException("Deck is empty.");
+    }
+
```
Comment (Markneoneo) [inline src/main/java/javatro/core/JavatroException.java:93]: Rmb to author your part once you merge my other PR

**Review by Markneoneo — APPROVED** [review]
LGTM
