### PR TITLE
Fix Exceeded Limit Text Occuring

### LINKED ISSUE #74: Bug in HoldingHand Play() and Discard()
`Exceeded Limit. Card not added.` shows up when playing or discarding cards in game. Below is an instance of the bug occurring when discarding 2 cards.

### Discards
```
Enter a number (1 to 2): 2
Enter numbers (comma-separated, e.g., 1,2,3) from 1 to 8 (Allowed to select only 8): 1,3 
You selected the numbers: [0, 2]
Exceeded Limit. Card not added.
```

### PR DESCRIPTION
**Pull request by jwyk**
Fix #74.

This PR introduces a fix for the `Exceeded Limit. Card not added.` text showing up when it is not intended to.

This was caused by the Round class and the `HoldingHand` class both using the `draw()` function to replenish cards drawn, causing more cards to be drawn then intended. This PR fixes this by removing the draw() section called in the `HoldingHand` class, and test suites were rewritten to align for the change in behavior.

### Round Class
```
       List<Card> playedCards = playerHand.play(cardIndices, this.deck);
        PokerHand result = HandResult.evaluateHand(playedCards);
        Integer totalChips = result.getChips();

        for (Card card : playedCards) {
            totalChips += card.getChips();
        }

        // Update round state
        currentScore += totalChips * result.getMultiplier();

        // Draw new cards to replace played ones
        playerHand.draw(POKER_HAND_SIZE, deck);
```

### HoldingHand Class
```
        for (int i = 0; i < numberOfDraws; i++) {
            if (Hand.size() < HOLDING_LIMIT) {
                Card tempCard = deck.draw();
                Hand.add(tempCard);
            } else {
                System.out.println("Exceeded Limit. Card not added.");
                break;
            }
        }

```

### CODE REVIEW

**Review by Markneoneo — APPROVED** [review]
LGTM

File: src/main/java/javatro_view/HelpScreen.java [hunk 1]
```diff
@@ -1,17 +1,18 @@
 package javatro_view;
 
-import javatro_manager.*;
```
Comment (flyingapricot) [inline src/main/java/javatro_view/HelpScreen.java:3]: No star imports should be used

**Review by flyingapricot — APPROVED** [review]
LGTM. Minor Fixes.
