### PR TITLE
Fix HoldingHand Play() and Discard()

### LINKED ISSUE #62: Bug in HoldingHand Play()
the indexes for `cardsToPlay` is no longer correct once `Hand.remove(play)` is ran.

```    public List<Card> play(List<Integer> cardsToPlay, Deck deck) {
        if (cardsToPlay.size() > 5) {
            System.out.println(
                    "Number of cards played "
                            + "("
                            + cardsToPlay.size()
                            + ")"
                            + "exceeds the maximum allowed. (5)");
            return null;
        }

        List<Card> playList = new ArrayList<>();
        for (int play : cardsToPlay) {
            Card card = Hand.remove(play);
            playList.add(card);
        }

        for (int i = 0; i < cardsToPlay.size(); i++) {
            Card tempCard = deck.draw();
            Hand.add(tempCard);
        }
        return playList;
    }
```

### PR DESCRIPTION
**Pull request by jwyk**
This PR fixes #62, while also adding `JavatroExceptions` for the `HoldingHand` class.

#62 was caused by `Hand` index positions shifting after every `Card` was removed, resulting in cards being played and discarded being incorrect. This PR fixes the issue by changing the logic flow.

Cards that should be removed are now removed in descending order when sorted. This eliminates the problem of index positions being shifted.

``` 
        List<Integer> sortedToRemove = new ArrayList<>(cardsToDiscard);
        sortedToRemove.sort(Comparator.reverseOrder());
        for (int index : sortedToRemove) {
            Hand.remove(index);
        }

```

For play(), cards that should be played use `Hand.get()` instead of `Hand.remove()` before the card removal step. This preserves the order of cards being played.

```
        // Add cards that should be played in order of cardsToPlay
        for (int index : cardsToPlay) {
            if (indicesToRemove.contains(index)) {
                Card card = Hand.get(index);
                playList.add(card);
            }
        }
```

### CODE REVIEW

File: src/main/java/Javatro/HoldingHand.java [hunk 1]
```diff
@@ -57,27 +60,49 @@ public void draw(int numberOfDraws, Deck deck) {
...
      * @param deck Deck containing the remaining cards
      */
-    public List<Card> play(List<Integer> cardsToPlay, Deck deck) {
+    public List<Card> play(List<Integer> cardsToPlay, Deck deck) throws JavatroException {
+        List<Card> playList = new ArrayList<>();
+
+        // Validate that cardsToPlay and the played card positions are valid inputs
         if (cardsToPlay.size() > 5) {
-            System.out.println(
+            throw new JavatroException(
```
Comment (K-J-Q) [inline src/main/java/Javatro/HoldingHand.java:68]: Might be good to create a method in JavatroException and `throw JavatroException.tooManyCardsPlayed()` instead

File: src/main/java/Javatro/HoldingHand.java [hunk 2]
```diff
@@ -57,27 +60,49 @@ public void draw(int numberOfDraws, Deck deck) {
...
+                Card card = Hand.get(index);
+                playList.add(card);
+            }
+        }
+
+        // Remove the cardsToPlay from the Hand in descending order of indices
+        List<Integer> sortedToRemove = new ArrayList<>(indicesToRemove);
+        sortedToRemove.sort(Comparator.reverseOrder());
+        for (int index : sortedToRemove) {
+            Hand.remove(index);
```
Comment (K-J-Q) [inline src/main/java/Javatro/HoldingHand.java:97]: Looks good! this should fix the bug

File: src/main/java/Javatro/HoldingHand.java [hunk 3]
```diff
@@ -88,9 +113,29 @@ public List<Card> play(List<Integer> cardsToPlay, Deck deck) {
...
      * @param deck Deck containing the remaining cards
      */
-    public void discard(List<Integer> cardsToDiscard, Deck deck) {
-        for (int discard : cardsToDiscard) {
-            Hand.remove(discard);
+    public void discard(List<Integer> cardsToDiscard, Deck deck) throws JavatroException {
+
+        // Validate that cardsToDiscard and the played card positions are valid inputs
+        if (cardsToDiscard.size() > 5) {
+            throw new JavatroException(
```
Comment (K-J-Q) [inline src/main/java/Javatro/HoldingHand.java:120]: Same here, could make a method in JavatroException instead

**Review by K-J-Q — APPROVED** [review]
Overall, LGTM!
