### PR TITLE
Fix Discards for HoldingHand

### LINKED ISSUE #117: Discards not showing up on screen
Upon discarding a hand, holdingHand is shown to be null.

```
Enter Option Index (1-6)
╰┈➤ 2
Transitioning to: DiscardCardScreen
╔══════════════════════════════════════════════════════════════════════════════════════════════════╗
║         <1>        <2>        <3>        <4>        <5>        <6>        <7>        <8>         ║
╠══════════════════════════════════════════════════════════════════════════════════════════════════╣
║       K          8          Q          5          3          7          9          8             ║
║                                                                                                  ║
║          H          H          S          S          H          H          H          S          ║
║                                                                                                  ║
║             K          8          Q          5          3          7          9          8       ║
╚══════════════════════════════════════════════════════════════════════════════════════════════════╝
╔══════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                 ::: SELECT CARDS TO DISCARD :::                                  ║
╠══════════════════════════════════════════════════════════════════════════════════════════════════╣
║                                         [1] Select Cards                                         ║
║                                      [2] Sort cards by Suit                                      ║
║                                      [3] Sort cards by Rank                                      ║
║                                       [4] View Poker Hands                                       ║
║                                          [5] View Deck                                           ║
║                                        [6] Return To Game                                        ║
╚══════════════════════════════════════════════════════════════════════════════════════════════════╝

Enter Option Index (1-6)
╰┈➤ 1
Enter Card Indices between 1-8. Up to 5 cards only. (e.g. 1,2,3,4,5)
╰┈➤ 1
Cannot invoke "java.util.List.size()" because "holdingHand" is null
```

### PR DESCRIPTION
**Pull request by jwyk**
The main focus of this PR is to fix #117, while adding the deck name to be displayed.

Upon discarding a hand, the chosen cards were not showing up, and an unexpected error demonstrated in #177 was showing up. It occured regardless of the number of cards played. Additionally, the `GameScreen` also failed to display, only showing options available. 

This bug occurred due to discards returning the cards, causing a null exception to occur. This has been fixed by changing the `discardCards()` in `RoundActions` to also return a `List` of Cards.

### CODE REVIEW

File: src/main/java/javatro/core/RoundActions.java [hunk 1]
```diff
@@ -102,7 +102,7 @@ public void discardCards(List<Integer> cardIndices) throws JavatroException {
         int oldRemainingDiscards = state.getRemainingDiscards();
 
         // Execute discard
-        round.playerHand.discard(cardIndices);
+        List<Card> discardedCards = round.playerHand.discard(cardIndices);
```
Comment (flyingapricot) [inline src/main/java/javatro/core/RoundActions.java:105]: Nice, great job finding the bug

**Review by flyingapricot — APPROVED** [review]
LGTM

File: src/main/java/javatro/core/Round.java [hunk 2]
```diff
@@ -324,6 +324,6 @@ public List<Card> getPlayedCards() {
      * @throws JavatroException If the played cards are invalid or empty
      */
     public PokerHand getPlayedHand() throws JavatroException {
-        return HandResult.evaluateHand(playedCards);
+        return HandResult.evaluateHand(chosenCards);
```
Comment (K-J-Q) [inline src/main/java/javatro/core/Round.java:327]: Good to have one variable for both!

**Review by K-J-Q — APPROVED** [review]
LGTM!
